env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  react/function-component-definition: 0
  react-hooks/exhaustive-deps: 0
  import/extensions: 0
  no-console: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  testing-library/no-debug: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
settings:
  react:
    version: detect
