env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  react/jsx-filename-extension: [0, { "extensions": [".js", ".jsx"] }]
  react/function-component-definition: 0
  react-hooks/exhaustive-deps: 0
  import/no-unresolved: 0
  import/extensions: 0
  no-console: 0
  react/prop-types: 0
  no-param-reassign: 0
settings:
  react:
    version: detect
